### ISSUE TITLE
increase performance splitEvery

### ISSUE THREAD

**Issue by xgbuils** [benji6/imlazy#26]
I'm reading about `splitEvery` and I've seen that maybe  #22 is the reason to do slice eager. However I think that maybe yo can optimize `splitEvery` without doing `slice` eager.

``` javascript
function* splitEvery(n, iterable) {
    const iterator = iterable[Symbol.iterator]()
    const chunk = []
    let state = iterator.next()
    let i = 0
    while(!state.done) {
        if (i < n) {
            chunk.push(state.value)
        } else {
            yield chunk
            chunk = [state.value]
            i = 0
        }
    }
    if (chunk.length > 0) {
        yield chunk
    } 
}
```

It has a little caveat: if `n === Infinity`, `splitEvery` could potentially use infinite cached data.

**Comment by benji6** [comment]
Yeah that's a good point - that sort of approach will be a lot faster than my current implementation, but it could also consume infinite memory if used in a crazy way! I'm probably not going to update my implementation of `splitEvery` because I think it's quite a niche function and unlikely to be a hot code path so I'll keep the simpler definition without having to worry about memory

**Comment by xgbuils** [comment]
Ok! Then, perfect.
