### ISSUE TITLE
Random considerations

### ISSUE THREAD

**Issue by ivan-kleshnin** [benji6/imlazy#7]
Cool library, Ben :+1: 

I've reviewed your API and it seems very close to Ramda.

My random *questionmarked* considerations:

1. Rename `makeCircular` to `cycle` just as it is in Haskell and Clojure?
http://hackage.haskell.org/package/base-4.8.1.0/docs/Prelude.html#v:cycle
https://clojuredocs.org/clojure.core/cycle

2. API lacks exact "typed" signatures. Unfortunately we're far from having common conventions for JS type notation. I like how Ramda adapts Haskell(-ish) notation, though. 

3. Difference bettween `assoc` and `insert`? Second one mimics Ramda while first one contradicts it.

4. Both Haskell and Ramda use `all` name for `every`. Clojure uses `every` though. 
Which one is better?

5. Implement [`sortBy`](http://ramdajs.com/docs/#sortBy) equivalent?

6. Use `freeze` only on production for better performance? [Example](https://github.com/gcanti/tcomb/blob/a100f030dc2d95f9e2371ef54ac4c15edf5c6139/lib/list.js#L51-L53).

Everything else seems predictable. Great. My appreciation!

**Comment by benji6** [comment]
Hey, thanks so much for taking such a thorough look at this! I really appreciate it. So addressing each of your points:

1. I overlooked this and you are right, `cycle` is a much better name, I think it's worth changing it
2. This definitely needs looking at and I also like the Haskell-ish notation
3. I suppose I envisioned `assoc` being more like Clojure's `assoc` in this case, which can be used on vectors as well as maps. The docs might not have been clear enough about how it works so I've reworded the description
4. I don't think there is really a correct answer to this, the main reason I went with `every` is because it's the name JS uses (as well as Clojure)
5. Happy to add `sortBy`
6. So I didn't consider that `Object.freeze` might have a performance cost, I've done some research and it seems that although this may once have been the case it is [no longer an issue](http://stackoverflow.com/questions/8435080/any-performance-benefit-to-locking-down-javascript-objects/23198265#23198265) so I think it's safe to leave this

**Comment by benji6** [comment]
#8

**Comment by benji6** [comment]
#9 rename `makeCircular` to `cycle`

**Comment by ivan-kleshnin** [comment]
Thank you! I'm glad I was helpful a bit. 
I'll try to use this lib in production soon ;)
